---
title: Making the Transcribing Process a Bit Simpler
author: Kyle Harris
date: '2018-06-10'
categories: ["R"]
tags: ["transcription", "tidyverse"]
---

# Follow Me On

<a href="https://twitter.com/KoderKow"> <i class='fab fa-twitter fa-3x'></i></a> <a href="https://www.instagram.com/koderkow/"> <i class='fab fa-instagram fa-3x'></i></a> <a href="https://github.com/KoderKow/"><i class='fab fa-github fa-3x'></i></a> <a href="https://koderkow.rbind.io"><i class='fas fa-globe fa-3x'></i></a>

# Intro

For the past year I have had the pleasure of working with the data visualization team at IUPUI. I approached Professor Reda looking to explore the realm of research. He gave me the opportunity to sit in their team meetings for the spring semester. As fall came around I joined the team.

For those who have worked in research, you may have crossed paths with user testing and the art of transcription. This was my first encounter with transcription and as the few jokes I heard about it, it wasn't/isn't that great of a time. With each user test being close to a hour, the time to transribe can be cumbersome. After some failed attemptes of hacky audio to text methods I ran into something that worked fairly well, YouTube!

YouTube makes auto closed captions for videos. Using their automation I was able to <b>privately</b> upload the videos and have them be transcribed fairly accurately. YouTube has a great UI for editing closed captions, allowing me to watch the full video with the auto generated captions to ensure accuracy. After that all that is left to do is download the file and convert it to a csv file.

During this process I added certain code words at the start of sentences, for example if any of the research members spoke during the test I started the line with "staff:". Later on this will help seperate the text into different columns (user text and staff text). If anyone is reading this that wants to do this for their transcription, feel free to make your own code words, you will have to change the R code a bit for the sbv to csv converter below. Sbv is the file format you save the YouTube close captionings.

There can be difficulties with this method. A big one is audio quality. Making sure the audio is clear with no background noise is important. I have had multiple videos be translated to spanish and german due to the service not being able to depict the language at the start. Another issue is two people talking at once. The service will get confused and try to choose a word that sounds like the words that both people are saying. Making sure one person speaks at a time ensures a easy transcription process. At worst YouTube does not auto transcribe for you. You can still make your own file on the site. There are convenient hotkeys to use while transcribing. Again, the UI is great for this type of work.

All around this method has saved our team a lot of time during the transcribing process. I wanted to share this method in hopes to save others who do transcriptions by ear. Below is a write I did for my team and the R code to convert the sbv files.

I want to emphasize about privacy. Videos are uploaded privately and deleted right after the process is complete. On top of that there is no way to identify any user in the videos due to not being able to see them.

Here is a great article that summarizes the work our research team does at IUPUI:

- [HCC faculty member awarded NSF grant for data visualization research](https://soic.iupui.edu/news/reda-nsf-crii-grant/)

1. Download the video(s) from box of the necessary session

2. Upload them to YouTube (you will need a YouTube/google account) 
    a. Make sure you set publish setting to PRIVATE! 
    b. Also make sure you delete the video after you are completely done  
\  
3. After the video has finished upload, it may take several hours for YouTube to automatically generate close captioning’s. 
    a. Close captioning’s will be our transcription in this case  
\  
4. To see if the automatic translation is complete, start at the homepage of YouTube 
    a. Click on the top right icon (your profile icon) and click ‘Creator Studio.’ 
    b. On the next page click ‘Video Manager’ on the left side. 
    c. Find the video you need on the list and click ‘Edit’ on that video 
    d. On the top menu, all the way to the right, click on ‘Subtitles/CC’ 
    e. To the right of the video underneath the blue bar that says ‘Add new subtitles or CC’ it will have a title that says ‘Published’ 
    f. If it has gone according to plan, it will say ‘English (Automatic)’. Click this. 
        - If it lists a different language, it means the audio quality was not clear and you will have to either start doing the transcription manually, or if you are efficient with video/audio editing you can try to clean up the audio 
        - If it does not show up at all after 6 hours, it will be due to the audio quality not being clear (from what I have read online) 
        
\  
5. After clicking ‘English (automatic)’ click edit on the top right 
\  
6. Get familiar with this layout! 
    a. You can click the times on the left to go directly to that spot on the timeline 
    b. You can edit the text directly while listening 
    c. Hotkeys I use: 
        - Shift + Space = play/pause 
        - Shift + Left/Right arrow = go forward/back a few seconds
        
\  
7. Listen to the whole video and read along with what is said in the video

\  
8. Important: When a member of the research team speaks start that line with ‘staff:’ 
    a. This is very important for the format of the final csv, I use this exact string to separate user text and staff text into separate columns in the R script.
    
\  
9. I manually insert a few important parts 
    a. When a video starts; ‘MVI 0001 Starts’ 
    b. When a video ends; ‘MVI 0001 Ends’ 
    c. When a question is SUBMITTED; ‘Q. I want to see…’ 
    d. When a graph is generated ‘\*\*Graph is Generated\*\*’
    
\  
10. Once you are happy with the entirety of the proof-read script, click on ‘Actions’ which is located right above the text editing area.

\  
11. Save it as a ‘.sbv’ file

\  
12. Once you have saved it you can message me and I can quickly do the rest, upload it to the box [Symbol] (I will add the R .sbv to .csv script soon) 

```{r, eval=FALSE, warning=FALSE, message=FALSE}
# If you do not have tidyverse:
# install.packages('tidyverse')
#
# CTRL + ENTER to run lines. run library and function.
#
# The last line is where you need to edit the
# string to files you want to edit

library(tidyverse)

sbv_to_csv <- function(filepath, savename){
  rawData <- read.table(filepath,
                    header = F,
                    sep = "\n",
                    quote="\"")
  
  rawData <- droplevels(rawData)
  rawData <- rawData %>% mutate(dont_keep = str_detect(rawData$V1, "0:"))
  
  # We decided we did not team time stamps (dont_keep)
  df <- data.frame(words = rawData %>%
                     filter(dont_keep == F) %>% select(V1))
  colnames(df) <- 'words'
  
  df$words <- as.character(df$words)
  
  df <- df %>% mutate(test = str_detect(words, 'staff:') |
                        str_detect(words, 'Staff:'),
                      interviewer = ifelse(test, words, ""),
                      text = ifelse(test, "", words))
  
# this line is for start/end time colums. fix select on line 26 to include this.
#transcribedData <- df %>% separate(time, c("startTime", "endTime"), ",")
  
  transcribedData <- df %>% select(text, interviewer)
  
  write.csv(transcribedData, file = savename)
}

# First param is path to file, if you are on windows
# you will need to escape the \, so "\\" as shown below
#
# Second param is the output, make sure it ends with
# .csv. this can also be a file path to save where you want it
#
# By default it is your documents I believe, or you
# can set your working directory with setwd(*FOLDERPATH*)

sbv_to_csv('C:...\\MVI_0115.sbv', '0115.csv')
```

<!-- ```{r echo=FALSE} -->
<!-- blogdown::shortcode('googleAdsense') -->
<!-- ``` -->
